[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "LLMConnect"
version = "0.1.0"
authors = [
    {name = "Moises-Tohias", email = "mousstouhami@gmail.com"},
]
description = "A Python HTTP client implementation for interacting with Large Language Model (LLM) providers"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/moisestohias/LLMConnect"
Documentation = ""
Repository = "https://github.com/moisestohias/LLMConnect.git"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
LLMConnect = ["*.json"]
